/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ScribEditor;

/**
 *
 * @author plpps
 */
public class ScribPadGui extends javax.swing.JFrame {

    /**
     * Creates new form ScribPadGui
     */
    public ScribPadGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textEditPane1 = new javax.swing.JTextPane();
        quickToolBar = new javax.swing.JToolBar();
        newFileTool = new javax.swing.JButton();
        openFileTool = new javax.swing.JButton();
        saveFileTool = new javax.swing.JButton();
        copyTextTool = new javax.swing.JButton();
        cutTextTool = new javax.swing.JButton();
        pasteTextTool = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newFile = new javax.swing.JMenuItem();
        openFile = new javax.swing.JMenuItem();
        saveFile = new javax.swing.JMenuItem();
        saveAsFile = new javax.swing.JMenuItem();
        PrintFile = new javax.swing.JMenuItem();
        exitFile = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutText = new javax.swing.JMenuItem();
        copyText = new javax.swing.JMenuItem();
        pasteText = new javax.swing.JMenuItem();
        selectAllText = new javax.swing.JMenuItem();
        searchMenu = new javax.swing.JMenu();
        findChar = new javax.swing.JMenuItem();
        findNextChar = new javax.swing.JMenuItem();
        findPreChar = new javax.swing.JMenuItem();
        replaceText = new javax.swing.JMenuItem();
        toolMenu = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        settingMenu = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(textEditPane1);

        quickToolBar.setRollover(true);
        quickToolBar.setAlignmentY(0.5F);

        newFileTool.setText("New");
        newFileTool.setToolTipText("New");
        newFileTool.setFocusable(false);
        newFileTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newFileTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        quickToolBar.add(newFileTool);

        openFileTool.setText("Open");
        openFileTool.setToolTipText("Open");
        openFileTool.setFocusable(false);
        openFileTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openFileTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        quickToolBar.add(openFileTool);

        saveFileTool.setText("Save");
        saveFileTool.setToolTipText("Save");
        saveFileTool.setFocusable(false);
        saveFileTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveFileTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveFileTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileToolActionPerformed(evt);
            }
        });
        quickToolBar.add(saveFileTool);

        copyTextTool.setText("Copy");
        copyTextTool.setToolTipText("Copy");
        copyTextTool.setFocusable(false);
        copyTextTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        copyTextTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        quickToolBar.add(copyTextTool);

        cutTextTool.setText("Cut");
        cutTextTool.setToolTipText("Cut");
        cutTextTool.setFocusable(false);
        cutTextTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cutTextTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        quickToolBar.add(cutTextTool);

        pasteTextTool.setText("Paste");
        pasteTextTool.setToolTipText("Paste");
        pasteTextTool.setFocusable(false);
        pasteTextTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pasteTextTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        quickToolBar.add(pasteTextTool);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(quickToolBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(quickToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fileMenu.setText("File");

        newFile.setText("New");
        fileMenu.add(newFile);

        openFile.setText("Open");
        fileMenu.add(openFile);

        saveFile.setText("Save");
        saveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileActionPerformed(evt);
            }
        });
        fileMenu.add(saveFile);

        saveAsFile.setText("Save As");
        fileMenu.add(saveAsFile);

        PrintFile.setText("Print");
        fileMenu.add(PrintFile);

        exitFile.setText("Exit");
        fileMenu.add(exitFile);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");

        cutText.setText("Cut");
        editMenu.add(cutText);

        copyText.setText("Copy");
        editMenu.add(copyText);

        pasteText.setText("Paste");
        editMenu.add(pasteText);

        selectAllText.setText("Select All");
        editMenu.add(selectAllText);

        jMenuBar1.add(editMenu);

        searchMenu.setText("Search");

        findChar.setText("Find");
        searchMenu.add(findChar);

        findNextChar.setText("Find Next");
        searchMenu.add(findNextChar);

        findPreChar.setText("Find Previous");
        searchMenu.add(findPreChar);

        replaceText.setText("Replace");
        searchMenu.add(replaceText);

        jMenuBar1.add(searchMenu);

        toolMenu.setText("Tools");

        jMenuItem16.setText("jMenuItem1");
        toolMenu.add(jMenuItem16);

        jMenuItem17.setText("jMenuItem1");
        toolMenu.add(jMenuItem17);

        jMenuItem18.setText("jMenuItem1");
        toolMenu.add(jMenuItem18);

        jMenuBar1.add(toolMenu);

        settingMenu.setText("Setting");

        jMenuItem19.setText("jMenuItem1");
        settingMenu.add(jMenuItem19);

        jMenuItem20.setText("jMenuItem1");
        settingMenu.add(jMenuItem20);

        jMenuItem21.setText("jMenuItem1");
        settingMenu.add(jMenuItem21);

        jMenuBar1.add(settingMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveFileActionPerformed

    private void saveFileToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileToolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveFileToolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScribPadGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScribPadGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScribPadGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScribPadGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScribPadGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem PrintFile;
    private javax.swing.JMenuItem copyText;
    private javax.swing.JButton copyTextTool;
    private javax.swing.JMenuItem cutText;
    private javax.swing.JButton cutTextTool;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitFile;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem findChar;
    private javax.swing.JMenuItem findNextChar;
    private javax.swing.JMenuItem findPreChar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem newFile;
    private javax.swing.JButton newFileTool;
    private javax.swing.JMenuItem openFile;
    private javax.swing.JButton openFileTool;
    private javax.swing.JMenuItem pasteText;
    private javax.swing.JButton pasteTextTool;
    private javax.swing.JToolBar quickToolBar;
    private javax.swing.JMenuItem replaceText;
    private javax.swing.JMenuItem saveAsFile;
    private javax.swing.JMenuItem saveFile;
    private javax.swing.JButton saveFileTool;
    private javax.swing.JMenu searchMenu;
    private javax.swing.JMenuItem selectAllText;
    private javax.swing.JMenu settingMenu;
    private javax.swing.JTextPane textEditPane1;
    private javax.swing.JMenu toolMenu;
    // End of variables declaration//GEN-END:variables
}
